장소에 색상 추가
boostcampwm-2024/web09-DailyRoad pull request #100
Opened 2024-11-11 07:32 UTC by Miensoap

## 📄 Summary

>장소에 색상 추가

## 🙋🏻 More

>지도에 장소 추가시 색상 선택
내용이 없는 페이지 요청에 대해 빈 배열 응답하도록 수정
전역 예외 필터 타입별로 분리

>필터는 뒤에 선언한 것이 우선순위가 높다
![image](https://github.com/user-attachments/assets/e86116d3-9128-418f-b53d-a711eae5e250)

![image](https://github.com/user-attachments/assets/cff978b1-0177-4498-b398-86024dd8eb69)

### 🕰️ Actual Time of Completion

> 1H

close #86

2024-11-11 16:13 UTC, koomchang requested changes
고생하셨습니다!

2024-11-11 16:13 UTC, koomchang commented on backend/resources/sql/DDL.sql
> +    color       VARCHAR(20) DEFAULT 'RED',
p1: NOT NULL 제약 조건이 빠진 것 같네요

2024-11-11 16:13 UTC, koomchang commented on backend/src/main.ts
> +    new BaseExceptionFilter(),
q: `BaseException`이 `HttpException`을 상속받기 때문에 실행 순서가 중요할 것 같은데요. `Filter`가 순서가 적용되는지 확인을 해야할 것 같습니다. 순서가 적용된다면 순서도 바꿔야 겠네요.

제가 테스트 했을 때는 효과가 없었던 것 같아서 `GlobalExceptionFilter`에서 `if` 로 구분했었거든요. 한번 확인해보고 알려주세요!

2024-11-11 16:13 UTC, koomchang commented on backend/src/map/map.service.ts
>      await this.checkPlaceCanAddToMap(placeId, map);
p3: `validatePlaceForMap()`  은 어떤가요!

2024-11-11 16:19 UTC, Miensoap commented on backend/src/main.ts
> +    new BaseExceptionFilter(),
이거 PR 메시지에 적었는데요,

당연히 좁은 범위를 먼저 선언해야 할 것 같지만
반대로 넓은 범위를 먼저 선언해야 제대로 작동하더라구요

2024-11-11 16:47 UTC, koomchang commented on backend/src/main.ts
> +    new BaseExceptionFilter(),
> 이거 PR 메시지에 적었는데요,
> 
> 당연히 좁은 범위를 먼저 선언해야 할 것 같지만 반대로 넓은 범위를 먼저 선언해야 제대로 작동하더라구요

헉 충격적이군요 좋습니다

2024-11-12 05:03 UTC, hyohyo12 approved these changes
수고했습니다!

2024-11-12 05:36 UTC, koomchang approved these changes

2024-11-12 05:50 UTC, merged