지도 서비스 단위 테스트, 지도 단위 테스트 작성 및 예외처리
boostcampwm-2024/web09-DailyRoad pull request #168
Opened 2024-11-23 07:09 UTC by hyohyo12

## 📄 Summary

 `map` 에 `addPlaceToMap` 메소드 등 유저 정보를 받고 사용하는 로직에 파라미터로 받은 유저 id 에 대한 유저 정보가 있는지 검증하는 로직이 없어 추가함.

`map` 에 대해서 공개, 비공개 전환하는 메소드에서 `isPublic` 에 어떤 값 어떤 타입이 와도 해당 값으로 `isPublic` 을 업데이트 하는 문제를 해결하기 위해 예외를 처리하는 로직 추가

`map` 에 대해서 `PermissionGuard` 를 달아서 어떤 유저가 다른 유저의 지도를 조작할 수 없게 함.

### 🕰️ Actual Time of Completion

> 20

2024-11-23 08:23 UTC, koomchang requested changes
고생하셨습니다.

줄바꿈과 같은 전체적인 코드 포맷팅에 신경을 써주면 좋을 것 같아요. 또 given, when, then 을 구분하여 줄바꿈을 넣으면 코드를 읽기 훨씬 수월할 것 같습니다.

모킹을 위에서 설정하고 내부에서 설정값을 쓰지 않고 다시 모킹을 하신 부분이 많던데,, 잘 찾아보시면 좋을 것 같습니다

2024-11-23 08:23 UTC, koomchang commented on backend/src/map/exception/TypeException.ts
> +      message: `${where} must be ${toType} not ${currentType}.`,
p1: 다른 `exception` 다 한글이면 이것도 통일해주세요

2024-11-23 08:23 UTC, koomchang commented on backend/src/map/guards/MapPermissionGuard.ts
> +    if (map.id !== userId) {
p1: `map`의 `userId`랑 비교해야하는 거 아닌가요?

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/integration-test/map.integration.util.ts
> +        inject: [DataSource],
```suggestion
        useValue: new PlaceRepository(dataSource),
```

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/integration-test/map.integration.util.ts
> +}
q: 어디서 사용하나요?

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +    } as unknown as jest.Mocked<MapRepository>;
p1: 위에서 타입 선언해줬는데 다시할 이유가 있나요?

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +  let placeRepository: jest.Mocked<PlaceRepository>;
p1: `Partial<jest.Mocked<MapRepository>>` 로 하면 아래에서도 unknown 이런거 줄일 수 있을 것 같네요. Partial을 사용하면 일부함수만 모킹할 수 있습니다.

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +  describe('searchMap 메소드 테스트', () => {
p1: 줄바꿈 신경써주세요

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +        expect.arrayContaining(
p3: 개인적인 바람으로 `given`, `when`, `then` 마다 줄바꿈이 있으면 좋을 것 같네요

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +        .mockResolvedValue(mockCoolMaps);
p1: 위에서 모킹했는데 왜 다시 `spyOn`을 사용하는걸까요?
```suggestion
      const spySearchByTitleQuery = mapRepository.searchByTitleQuery.mockResolvedValue(mockCoolMaps)
```

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +        'cool',
p1: `const searchTitle = 'cool';` 로 정의한 부분을 사용하면 되지 않나요?

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +        where: { title: 'cool', isPublic: true },
p1: const searchTitle = 'cool'; 로 정의한 부분을 사용하면 되지 않나요?

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.test.util.ts
> +}
p2: 외부에서 이 함수를 보면 `count`의 의미가 뭔지 모를 것 같아요. 더 나은 메소드명이 없을까요?
+ 고차함수를 사용하면 좋을 것 같습니다

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +      });
p2: `toHaveBeenCalledWith()` 는 굳이 테스트 하지 않아도 될 것 같습니다. 혹시 테스트하는 이유가 있나요?

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +      const spyOnExistById = mapRepository.existById.mockResolvedValue(false);
q: 여기는 모킹한걸 잘 쓰셨네요? 이런 식으로 다 통일하면 좋을 것 같네요

2024-11-23 08:23 UTC, koomchang commented on backend/test/map/map.service.test.ts
> +    it('업데이트 하려는 지도가 있을 경우 지도를 파라미터의 정보로 업데이트 한다.', async () => {
p1: 줄바꿈 신경써주세요

2024-11-23 08:48 UTC, Miensoap requested changes
수고하셨습니다.

컨트롤러 (통합) 테스트 작업도 완료하신 것으로 들었는데,  
다음 PR 에 반영되나요?

2024-11-23 08:48 UTC, Miensoap commented on backend/src/map/guards/MapPermissionGuard.ts
> +export class MapPermissionGuard implements CanActivate {
p2. 항상 함께 사용될 것 같은데 인증 가드를 상속해 사용하면 어떨까요?
불필요한 컨트롤러 인자와 가드 사용 코드를 줄일 수 있을 것 같아요.

참고 : `AdminGuard`

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/integration-test/map.integration.util.ts
> +  parts[1] = Buffer.from('{"userId":1,"role":"admin"}').toString('base64'); // 조작된 페이로드
p3. 주석 없이는 이해가 어렵다면 변수명을 활용해 보는건 어떨까요?
```ts
const [header, payload, signature] = validToken.split('.');
const manipulatedPayload = Buffer.from('{"userId":1,"role":"admin"}').toString('base64');

return [header, manipulatedPayload, signature].join('.');
```

추가로, 이미 내용이 저것과 동일하면 조작 후에도 검증에 성공하나요?

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/map.service.test.ts
> +    it('파라미터 중 쿼리(지도 title)가 있을 경우 해당 제목을 가진 지도들을 반환한다', async () => {
p3. 쿼리가 어떻게 적용되는지 외부로 알리지 않으니,  `(지도 title)` 설명은 없어도 될 것 같아요.

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/map.service.test.ts
> +      expect(result.totalPages).toEqual(
p2. 페이징 관련 테스트는 분리해서 할 수도 있겠네요.
- 1페이지보다 작은 결과인 경우
- 1페이지 초과하는 결과인 경우
- 결과가 없는 경우
- 페이지 크기와 일치하는 결과 수인 경우 총 페이지 수는 어떻게 반환되는지

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/map.service.test.ts
> +      expect(result.totalPages).toEqual(
특히 모킹한 부분을 중복해서 검증할 필요 없을 것 같아요.

>`a()` 호출하면 2가 나오도록 모킹 -> 결과가 2인지 검증이 필요할까?

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/map.service.test.ts
> +      expect(result).toEqual(expect.objectContaining({ id: undefined }));
q. `expect.objectContaining({ id: undefined }));` 이건 뭘 검증하는건가요?

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/map.service.test.ts
> +      const spyOnSave = mapRepository.save.mockResolvedValue(resolvedMap);
p2. 모킹 코드와 테스트 코드가 섞이지 않게 메서드 맨 위에 작성하면 어떨까요?

저는 `모킹한 부분 (레포지토리) 이 ~~ 한 응답을 할 것이다. `
는 given 에 속한다고 생각하는데, 동효님은 어떻게 생각하시나요?

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/map.service.test.ts
> +    it('장소를 추가하려는 지도가 있을 경우 장소를 추가하고 장소 정보를 다시 반환한다.', async () => {
p3. 굳이 조건을 표현하려면
`장소를 추가하려는 지도가 존재하고, 추가하려는 장소가 존재하는 경우`

인 것 같은데,  **반대 상황에 대한 테스트**를 잘 작성해 주신 것 같아서,  
저는 정상 상황에 대한 테스트는 모든 상황을 나열하지 않아도 될 것 같아요.

동효님은 어떻게 생각하시나요?
**상세히 작성하는 쪽을 선호**하신다면,  위처럼 **모든 조건을 명시**해야 할 것 같아요.


`업데이트 하려는 지도가 있을 경우` 도 동일

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/map.service.test.ts
> +    it('mapId로 받은 지도에서 placeId 를 제거하고 해당 placeId 를 반환한다.', async () => {
p3. 여긴 조건이 없네요. 둘 중 하나로 통일되면 좋겠습니다.

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/map.test.util.ts
> +export function createPublicMaps(count: number, user: User) {
p2. `public test map ${i}`` 이부분에 대한 설명이 메서드명에 더 잘 나타나면 좋겠어요.
어떤 공개 지도를 만드는지?

2024-11-23 08:48 UTC, Miensoap commented on backend/test/map/map.test.util.ts
> +      title: `${title} ${i}`,
여기도 동일.
주석으로라도 남기는게 어떨까요?

세부 구현을 모르는 팀원이 
>"난 aaa 라는 이름의 지도를 만들려도 했는데 왜 aaa 1 이 만들어지는거야?"
라고 생각할 수 있을 것 같아요.

2024-11-25 01:13 UTC, hyohyo12 commented on backend/src/map/guards/MapPermissionGuard.ts
> +    if (map.id !== userId) {
아... 실수했네요.

2024-11-25 01:14 UTC, hyohyo12 commented on backend/test/map/integration-test/map.integration.util.ts
> +}
위 함수는 필요없는데 아래 함수는 일부로 올바르지 않은 토큰을 만드는데 사용됩니다.

2024-11-25 01:38 UTC, hyohyo12 commented on backend/test/map/map.service.test.ts
> +    } as unknown as jest.Mocked<MapRepository>;
TypeScript 에서 mapRepository 의 타입을 `jest.Mocked<MapRepository>` 이렇게 선언하면 `mapRepository` 는 모든 메소드가 jest mock 함수여야 하는데 객체로 직접 선언할 때 해당 jest.fn 들이 mock 보다는 일반 메소드로 인식되기에 이와 같이 단언 한번 더 했습니다. `createMock` 을 이용해서 좀 더 직관적으로 보이게 수정하겠습니다.

2024-11-25 01:39 UTC, hyohyo12 commented on backend/test/map/map.service.test.ts
> +        where: { title: 'cool', isPublic: true },
좋습니다!

2024-11-25 02:00 UTC, koomchang commented on backend/test/map/integration-test/map.integration.util.ts
> +}
> 위 함수는 필요없는데 아래 함수는 일부로 올바르지 않은 토큰을 만드는데 사용됩니다.

코드 상에서 사용하신 곳이 없는 것 같습니다

2024-11-25 04:28 UTC, hyohyo12 commented on backend/test/map/map.test.util.ts
> +}
좋습니다!

2024-11-25 04:30 UTC, hyohyo12 commented on backend/test/map/map.service.test.ts
> +      });
`count` 를 모킹해서 사용하다보니 해당 메소드가 정확한 데이터를 가지고 조회를 하는지 검사하기 위해서 테스트 진행하려고 했습니다!

2024-11-25 04:30 UTC, hyohyo12 commented on backend/test/map/map.service.test.ts
> +      const spyOnExistById = mapRepository.existById.mockResolvedValue(false);
감사합니다!

2024-11-25 04:30 UTC, hyohyo12 commented on backend/test/map/map.service.test.ts
> +    it('업데이트 하려는 지도가 있을 경우 지도를 파라미터의 정보로 업데이트 한다.', async () => {
넵

2024-11-25 16:58 UTC, hyohyo12 commented on backend/test/map/map.service.test.ts
> +    it('장소를 추가하려는 지도가 있을 경우 장소를 추가하고 장소 정보를 다시 반환한다.', async () => {
저는 일단 정상적인 상황이더라도 정상적인 값이 오나? 이것도 테스트 하고 싶어서.. 좀 더 고민해보겠습니다!

2024-11-25 16:58 UTC, hyohyo12 commented on backend/test/map/map.test.util.ts
> +export function createPublicMaps(count: number, user: User) {
넵!

2024-11-26 05:32 UTC, hyohyo12 commented on backend/src/map/map.service.ts
> +  private async checkPublicType(isPublic: any) {
코드 중복 해결, 보안, 테스트 용이성 등 좋은 이유가 있네요!...

2024-11-26 05:33 UTC, hyohyo12 commented on backend/test/map/integration-test/map.integration.util.ts
> +}
그 초반에 JwtToken 잘 작동하는지 테스트할 때 사용돼요!
```ts
      token = jwtHelper.generateToken('24h', payload);
      const invalidToken = createInvalidToken(token);

      return request(app.getHttpServer())
        .get('/maps/my')
        .set(`Authorization`, `Bearer ${invalidToken}`)

        .expect(401);
```

2024-11-26 05:34 UTC, hyohyo12 commented on backend/src/map/exception/TypeException.ts
> +      message: `${where} must be ${toType} not ${currentType}.`,
넵!!

2024-11-26 06:12 UTC, Miensoap approved these changes

2024-11-26 06:12 UTC, Miensoap commented on backend/src/map/exception/UserNotFoundException.ts
> +export class UserNotFoundException extends BaseException {
p1. 유저 모듈에 이미 같은 예외가 있을거에요

2024-11-26 06:12 UTC, Miensoap commented on backend/test/map/map.service.test.ts
> +    await placeRepository.query(`ALTER TABLE PLACE AUTO_INCREMENT = 1`);
~~p2. 이정도는 분리해도 좋겠네요~~

이후에 테스트 리팩터링할때 공통으로 수정할게요

2024-11-26 06:19 UTC, Miensoap requested changes

2024-11-26 06:19 UTC, Miensoap commented on backend/src/map/map.service.ts
> +  private async checkUserExist(userId: number) {
p1. 탈퇴 기능이 없어서 지금은 확인 안해도 될 것 같은데요?

탈퇴가 생기면 redis 등으로 블랙 리스트를 적용해 
탈퇴한 유저의 엑세스 토큰으로 접근을 막을 것 같아요.

2024-11-26 06:58 UTC, hyohyo12 commented on backend/src/map/map.service.ts
> +  private async checkUserExist(userId: number) {
알겠습니다.

2024-11-26 07:13 UTC, Miensoap approved these changes
수고하셨습니다.

2024-11-26 07:20 UTC, koomchang requested changes

2024-11-26 07:20 UTC, koomchang commented on backend/package.json
> +    "@golevelup/ts-jest": "^0.6.1",
q: 무슨 용도인가요?

2024-11-26 07:20 UTC, koomchang commented on backend/src/map/map.controller.ts
> +    @Query('limit', new ParseOptionalNumberPipe(15)) limit?: number,
p2: 여기 바꿀거면 코스도 같이 바꿔주면 좋을 것 같네요

2024-11-26 07:20 UTC, koomchang commented on backend/test/map/integration-test/map.integration.expectExcptions.ts
> +};
p1: 안 쓰이는 것 같은데 지우는게 좋아보입니다!

2024-11-26 07:20 UTC, koomchang commented on backend/test/map/integration-test/map.integration.util.ts
> +        inject: [DataSource],
아직 안 바꾸셨네요!

2024-11-26 07:40 UTC, hyohyo12 commented on backend/test/map/integration-test/map.integration.util.ts
> +        inject: [DataSource],
저번엔 에러가 나던데,,,, 지금 또 다시 바꾸니깐 해결됐네요.. 원인을 찾아봐야겠어요

2024-11-26 07:40 UTC, hyohyo12 commented on backend/src/map/exception/UserNotFoundException.ts
> +export class UserNotFoundException extends BaseException {
넵!

2024-11-26 07:40 UTC, hyohyo12 commented on backend/test/map/map.service.test.ts
> +    await placeRepository.query(`ALTER TABLE PLACE AUTO_INCREMENT = 1`);
추후 분리할 부분 분리해야겠습니다..

2024-11-26 07:41 UTC, hyohyo12 commented on backend/package.json
> +    "@golevelup/ts-jest": "^0.6.1",
예전 목킹하는 부분인데 삭제를 못했네요. 정정하겠습니다.

2024-11-26 07:43 UTC, hyohyo12 commented on backend/test/map/integration-test/map.integration.expectExcptions.ts
> +};
자주 사용되는 예상되는 예외들을 모아놔서 중복 코드 줄이는데 또는 분리한데 사용됩니다. 나중에 리펙토링하면서 필요없는 부분 삭제하겠습니다.

2024-11-26 07:46 UTC, hyohyo12 commented on backend/src/map/map.controller.ts
> +    @Query('limit', new ParseOptionalNumberPipe(15)) limit?: number,
그러게요! 수정하고 push 하겠습니다

2024-11-26 07:48 UTC, koomchang commented on backend/test/map/integration-test/map.integration.expectExcptions.ts
> +};
현재 작성하신 코드 상에서 사용 안 하지 않나요?

2024-11-26 08:01 UTC, hyohyo12 commented on backend/test/map/map.service.test.ts
> +    const module: TestingModule = await Test.createTestingModule({
처음 테스트 목적 중 하나가 각각의 테스트가 독립적으로 수행될 수 있도록 환경을 만드는 것인데 각 테스트랑 환경을 격리할 수 있어서 `beforeEach` 에 넣었습니다. 현재 초기화하는 부분도 그렇게 무겁지 않다고 생각해서요. 추후 오버헤드 등 발생할 가능성 있으면 `beforeAll` 로 옮기겠습니다.

2024-11-26 08:10 UTC, koomchang approved these changes

2024-11-26 08:14 UTC, merged