코스 생성/삭제/조회/검색/수정 API 구현
boostcampwm-2024/web09-DailyRoad pull request #60
Opened 2024-11-06 07:07 UTC by Miensoap

## 📄 Summary

> https://documenter.getpostman.com/view/29034241/2sAY4yefx2#cbc5d798-d6f4-4511-8f42-e6f62abd241c

## 🙋🏻 More

> 지도/코스 내 장소 조회에서 한줄평 포함하도록 수정
확인되지 않은 에러 발생시 에러 로깅 추가

### 🕰️ Actual Time of Completion

> 2H

2024-11-06 07:40 UTC, koomchang requested changes

2024-11-06 07:40 UTC, koomchang commented on backend/src/common/exception/filter/GlobalExceptionFilter.ts
> +      console.log(exception);
q: 나중에 로깅으로 바꾸는 거 표시하려고 해두신건가요?

2024-11-06 07:40 UTC, koomchang commented on backend/src/course/course.repository.ts
> +      where: { user: { id: userId }, deletedAt: null },
p1: `find()` 함수에 `deletedAt: null` 처리가 되어 있어서 빼도 될 것 같습니다

2024-11-06 07:40 UTC, koomchang commented on backend/src/course/course.service.ts
> +    throw new CourseNotFoundException(id);
p2: 부정일 때 `Exception` 던지는게 자연스러워 보이네요
```suggestion
    if (!(await this.courseRepository.findById(id);)) throw new CourseNotFoundException(id);
    
    return await CourseDetailResponse.from(map);
```

2024-11-06 07:40 UTC, koomchang commented on backend/src/course/dto/CreateCourseRequest.ts
> +    const form = new CreateCourseRequest();
p2: `form` 대신 `request`로 바꾸면 좋을 듯 합니다

2024-11-06 07:40 UTC, koomchang commented on backend/src/user/user.entity.ts
> +import { Course } from '../course/entity/course.entity';
q: `entity` 디렉토리는 다시 설정하는 걸로 바꾸신건가요? 맞다면 `TypeOrmConfigService`에서 `entities` 경로도 추가적으로 바꿔야 할 것 같습니다.

2024-11-06 07:42 UTC, Miensoap commented on backend/src/user/user.entity.ts
> +import { Course } from '../course/entity/course.entity';
지도랑 맞춘건데 유저/장소는 엔티티 디렉토리가 없네요! 
둘중 하나로 통일하면 될 것 같습니다.

경로 추적은 `**` 경로 사용해서 `.entity.ts` 면 식별하게 설정되어 있어서 수정 안해도 될 거에요.

2024-11-06 07:43 UTC, Miensoap commented on backend/src/common/exception/filter/GlobalExceptionFilter.ts
> +      console.log(exception);
넵
 당장 로거 사용하지 않아도 확인되지 않은 에러는 출력되어야 할 것 같아요.

2024-11-06 07:44 UTC, Miensoap commented on backend/src/course/course.repository.ts
> +      where: { user: { id: userId }, deletedAt: null },
지금보니 map 에도 같은 실수가 있네요 ㅎㅎ

2024-11-06 07:49 UTC, koomchang commented on backend/src/user/user.entity.ts
> +import { Course } from '../course/entity/course.entity';
개인적으로는 `entity` 디렉토리가 있는게 좋을 것 같다고 생각해요! 있는 쪽으로 통일할가요?

2024-11-06 07:50 UTC, koomchang approved these changes
수고하셨습니다!

2024-11-06 07:59 UTC, Miensoap commented on backend/src/user/user.entity.ts
> +import { Course } from '../course/entity/course.entity';
헉 다 없앴는데 ㅋㅋ 
이후에 파일 네이밍 파스칼케이스로 간다면 저도 있는게 나을 것 같아요!

2024-11-06 08:11 UTC, koomchang commented on backend/src/user/user.entity.ts
> +import { Course } from '../course/entity/course.entity';
ㅎㅎ 그럼 있는쪽으로 가시죠!

2024-11-06 08:22 UTC, Miensoap commented on backend/src/user/user.entity.ts
> +import { Course } from '../course/entity/course.entity';
넵 ㅎㅎ 있는 걸로 통일했습니다~

2024-11-06 11:14 UTC, Miensoap commented
#64  이거먼저 머지하고 제가 confict 해결하고 머지할게요

2024-11-07 06:24 UTC, hyohyo12 approved these changes
수고하셨습니다!

2024-11-07 09:03 UTC, merged