구글 소셜 로그인을 지원하는 유저, Auth 모듈 구현
boostcampwm-2024/web09-DailyRoad pull request #64
Opened 2024-11-06 10:04 UTC by hyohyo12

## 📄 Summary

> 구글 OAuth Api 를 이용해서 소셜 로그인 구현
Jwt 를 통해 클라이언트로 토큰 전달
JwtGuard 구현
map.service 에서 UserRepository 주입 방식 변경

## 🙋🏻 More

> 최근 TypeORM 에서 `@InjectRepository(User)` 를 사용하지 못해서 직접 주입해서 사용

### 🕰️ Actual Time of Completion

> 16

2024-11-06 11:06 UTC, Miensoap requested changes
린트 깨지는 건 제가 수정해서 올려놨어요!
pull 한번 하시고 리뷰 확인해 주세요~

2024-11-06 11:06 UTC, Miensoap commented on backend/src/auth/auth.service.ts
> +      typeof response.refresh_token === 'string'
p1. 위에서 타입 확인하고 있는데 `stirng`인지 또 확인해야 하나요?

2024-11-06 11:06 UTC, Miensoap commented on backend/src/auth/auth.service.ts
> +      typeof response.name === 'string'
동일. 
추가로 response 존재하는지 확인도 
`is googleUserResponse` 에서 체크 될 것 같아요.

2024-11-06 11:06 UTC, Miensoap commented on backend/src/user/user.service.ts
> +  async saveUser(userInfo: userInfoWithProvider) {
p1. 여기서 id (PK) 를 반환해서 토큰에 담는건 어떨까요?
이후 권한 확인에서 db 조회를 생략할 수 있을 것 같아요.

2024-11-06 12:58 UTC, koomchang requested changes
정말 고생 많으십니다.. 슬슬 끝이 보이네요

2024-11-06 12:58 UTC, koomchang commented on backend/src/auth/auth.service.ts
> +  }
p2: 좋습니다! 예기치 못한 에러를 잡기 위해 `catch`를 추가로 에러 처리 해주는 것도 좋을 것 같네요

2024-11-06 12:58 UTC, koomchang commented on backend/src/auth/auth.service.ts
> +        }
p2: 마찬가지 `catch` 로 예기치 못한 에러처리 하면 좋을 것 같습니다!

2024-11-06 12:58 UTC, koomchang commented on backend/src/auth/auth.service.ts
> +          picture: data?.picture,
q: `picture`는 구글에서 주는 데이터명인건가요?

2024-11-06 12:58 UTC, koomchang commented on backend/src/user/user-role.ts
> +  MEMBER,
p2: 게스트는 유저 정보가 저장되지 않을 텐데 가지고 있을 이유가 없어보입니다!

2024-11-06 12:58 UTC, koomchang commented on backend/src/user/user.controller.ts
> +@Controller('user')
p1: REST API에서 URL 도메인은 복수를 권장합니다!

2024-11-06 12:58 UTC, koomchang commented on backend/src/user/user.repository.ts
> +  private readonly repository: Repository<User>;
p1: 필요 없는 부분 같습니다!

2024-11-06 12:58 UTC, koomchang commented on backend/src/user/user.repository.ts
> +    this.repository = dataSource.getRepository(User);
p1: 필요 없는 부분 같습니다!

2024-11-06 12:58 UTC, koomchang commented on backend/src/user/user.repository.ts
> +      } as FindOptionsWhere<User>,
p1: `TypeORM`에서 추론가능하여 `as` 는 없어도 될 것 같습니다

2024-11-06 12:58 UTC, koomchang commented on backend/src/user/user.repository.ts
> +  }
p1: `undefined` 일 때 예외처리가 되어있지 않습니다. `Promise<User>`로 반환하고 Service 단에서 예외처리를 추가하면 좋을 것 같습니다.

2024-11-06 12:58 UTC, koomchang commented on backend/src/user/user.repository.ts
> +  }
p1: 참고해서 바꾸면 좋을 것 같아요

```ts
//src/place/place.service.ts

async addPlace(createPlaceRequest: CreatePlaceRequest) {
    const { googlePlaceId } = createPlaceRequest;
    if (await this.placeRepository.findByGooglePlaceId(googlePlaceId)) {
      throw new PlaceAlreadyExistsException();
    }

    const place = createPlaceRequest.toEntity();
    const savedPlace = await this.placeRepository.save(place);
    return { id: savedPlace.id };
  }
```

2024-11-06 12:58 UTC, koomchang commented on backend/src/user/user.service.ts
> +      { conflictPaths: ['id'] },
q: `{ conflictPaths: ['id'] },` 의 역할이 뭔가요?

2024-11-06 13:03 UTC, Miensoap commented on backend/src/user/user.service.ts
> +      { conflictPaths: ['id'] },
p1. oauthId 가 conflictPaths 가 되야 할 것 같네요.

>q: { conflictPaths: ['id'] }, 의 역할이 뭔가요?
존재하지 않는다면 insert 해주는 기준입니다!

2024-11-07 01:50 UTC, hyohyo12 commented on backend/src/auth/auth.service.ts
> +      typeof response.refresh_token === 'string'
중복 확인 수정하겠습니다!

2024-11-07 02:55 UTC, hyohyo12 commented on backend/src/auth/auth.service.ts
> +      typeof response.refresh_token === 'string'
저 부분이 있어야 구글에서 정상적으로 맞는 `code` 가 왔는지 검증까지해서 만약 옳지 않은 `code` 를 준다면 
token: { error: 'invalid_grant', error_description: 'Malformed auth code.' }
이런 방식으로 주기에 `code` 가 정상적인지 확인하는 로직을 같이하고 있습니다.

2024-11-07 02:55 UTC, hyohyo12 commented on backend/src/auth/auth.service.ts
> +      typeof response.name === 'string'
위와 같이 같은 역할을 하는 중입니다..

2024-11-07 02:56 UTC, hyohyo12 commented on backend/src/user/user.service.ts
> +  async saveUser(userInfo: userInfoWithProvider) {
넵 알겠습니다!

2024-11-07 02:57 UTC, hyohyo12 commented on backend/src/auth/auth.service.ts
> +  }
넵 `catch` 추가 하겠습니다!

2024-11-07 02:57 UTC, hyohyo12 commented on backend/src/auth/auth.service.ts
> +        }
넵!

2024-11-07 02:58 UTC, hyohyo12 commented on backend/src/auth/auth.service.ts
> +          picture: data?.picture,
네네 구글에서 그렇게 명명해서 줍니다..

2024-11-07 02:58 UTC, hyohyo12 commented on backend/src/user/user-role.ts
> +  MEMBER,
아하 넵 정정하겠습니다!

2024-11-07 02:58 UTC, hyohyo12 commented on backend/src/user/user.controller.ts
> +@Controller('user')
오오오 몰랐던 사실이네요.. 감사합니다!

2024-11-07 03:00 UTC, hyohyo12 commented on backend/src/user/user.repository.ts
> +    this.repository = dataSource.getRepository(User);
필요없는 부분 지우겠습니다!

2024-11-07 03:01 UTC, hyohyo12 commented on backend/src/user/user.repository.ts
> +  }
오 감사합니다.

2024-11-07 05:28 UTC, hyohyo12 commented on backend/src/user/user.repository.ts
> +  }
`createUserRequest` 클래스를 만들고 나서 저장하는 방식 맞죠???

2024-11-07 06:38 UTC, Miensoap requested changes

2024-11-07 06:38 UTC, Miensoap commented on backend/src/user/user.service.ts
> +// import { userInfoWithProvider } from './userType';
p2. 주석제거

2024-11-07 06:38 UTC, Miensoap commented on backend/src/user/user.service.ts
> +    if (existingUser) {
p1. `findByProviderAndOauthId` 에서 항상 유저를 반환 
( provider, oauthid를 기준으로 upsert로 저장하고 정보 반환 ) 하면 
여기서 분기 처리가 필요 없을 것 같아요.

![image](https://github.com/user-attachments/assets/1e80b30b-6905-41bf-a5b4-a0b71262b9a5)

> 해당 로직을 표현하는 이름이면 더 좋겠네요
> `InsertResult` 타입 확인해 보시고 , find 없이 저기서 꺼내올 수 있다면 사용

2024-11-07 07:34 UTC, hyohyo12 commented on backend/src/user/user.service.ts
> +    if (existingUser) {
upsert 를 사용하지 않았던 이유가 처음에 `member` 로 role 을 정하는데 만약에 `admin` 이라는 role 을 가진다면 로그인 할 때마다 role 이 `member` 로 변하기에 선택하긴 했습니다. 다른 좋은 방법이 있을까요? upsert 를 사용하면서 role 이 로그인할 때 불변하게 되는...

2024-11-07 07:34 UTC, hyohyo12 commented on backend/src/user/user.service.ts
> +// import { userInfoWithProvider } from './userType';
놓쳤네요..

2024-11-07 08:09 UTC, Miensoap commented on backend/src/user/user.service.ts
> +    if (existingUser) {
아하 다른 다른 문제가 엮여있었군여
어드민 토큰은 따로 발급하는 등... 

그럼 일단 두고 더 이야기해 보아요!

2024-11-07 08:12 UTC, hyohyo12 commented on backend/src/user/user.service.ts
> +    if (existingUser) {
넵 그건 따로 생각해봐야겠습니당..ㅠㅠ 권한 페이지나 권한 부여 방식? 이런 세부사항 정해지면 수정하겠습니다!

2024-11-07 08:15 UTC, koomchang requested changes

2024-11-07 08:15 UTC, koomchang commented on backend/src/auth/auth.controller.ts
> +  @HttpCode(201)
p2: `Post` 기본값이 201이라 없어도 될 것 같아요

2024-11-07 08:15 UTC, koomchang commented on backend/src/auth/auth.service.ts
> +      expiresIn: '24h',
p2: jwt expiration도 env로 옮길 수 있으면 좋을 것 같아요

2024-11-07 08:15 UTC, koomchang commented on backend/src/user/user-role.ts
> +  MEMBER,
아직 안 바뀐 것 같네요!

2024-11-07 08:15 UTC, koomchang commented on backend/src/user/user.controller.ts
> +@Controller('user')
여기도 아직..

2024-11-07 08:54 UTC, koomchang approved these changes
고생하셨습니다!

2024-11-07 08:55 UTC, Miensoap approved these changes
^^

2024-11-07 08:55 UTC, merged